title: Riley Francis
logo: /assets/img/logo.png
description: Student, researcher, and outdoors enthusiast. Hi, I'm Riley! \n CS & Math @ UConn
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
